### ISSUE TITLE
Wayland support roadmap, second run

### ISSUE THREAD

**Issue by vberger** [tomaka/glutin#577]
I create this issue to track what is still missing for the wayland backend:

Window API:
- [ ] show/hide
- [ ] {get,set}_position => not available on core wayland protocol
- [x] get_outer_size
- [ ] set_cursor
- [ ] hidpi_factor
- [ ] set_cursor_position => not available on core wayland protocol
- [ ] platform_{display,window} => ???

Events:
- [x] Resized
- [ ] Moved => not available on core wayland protocol
- [ ] Closed => not available on core wayland protocol, doable with self-drawn decorations
- [ ] DroppedFile
- [ ] Focused
- [ ] MouseWheel
- [ ] Awakened
- [ ] Suspended
- [ ] Touch

Glutin specific API
- [ ] min_size / max_size

**Comment by vberger** [comment]
Just to give some feedback: I'm not advancing a lot here, mostly because there are some chances going on on the side of wayland developers.

With other binding writers, we agreed to push some changes to the protocol specification to make it more type-safe. Once this is done, I'll need to update my bindings to make profit of these type information. And it'll be a big breaking change. (Hopefully it should be doable in at most 1 or 2 weeks)

Hence, I don't really want to build a huge thing in glutin, just to break it apart 2 weeks after.... But once all this stuff is clear, I'll get back to making all this work. :smile:

**Comment by vberger** [comment]
cc #674

**Comment by Binero** [comment]
Window decorations don't seem to work. Not sure what that'd fall under.

**Comment by vberger** [comment]
Can you be more explicit about "don't seem to work" ?

There should be basic (ugly) decorations allowing resize and move at the moment.

**Comment by Binero** [comment]
Off topic for the above discussion; the following code gives an error. I am guessing it's a feature that isn't implemented, without a proper warning message to go with it.

```rust
let builder = WindowBuilder::new().with_title("Inspiration.".to_string()).with_decorations(true).with_min_dimensions(200, 200).with_max_dimensions(1280, 720);
```

```
thread '<main>' panicked at 'assertion failed: window.min_dimensions.is_none()', /src/api/wayland/window.rs:145
```

It gives a similar error for maximum dimensions.

**Comment by Binero** [comment]
To elaborate on the windows decoration issue, this is what gets rendered for a basic window: 

![Example Render](http://i.imgur.com/SI1kQ8R.png)

The relevant code: 
```rust
let builder = WindowBuilder::new().with_title("Inspiration.".to_string())
                                                      .with_decorations(true)
                                                      .with_dimensions(1280, 720);
```

The window does not allow for moving or resizing. It does not show a mouse when hovered over.

**Comment by vberger** [comment]
Regarding min/max_dimensions, yeah, it's not implemented (I guess at some point it go implemented for other backends but not wayland), I'll add it to the list.

Regarding your window, well the render result looks like what should be expected at least.

So, rezising the window by grabbing a border does not work ? Which compositor are you using, I only tested with Weston.

**Comment by Binero** [comment]
I am running GNOME.

**Comment by vberger** [comment]
Wan you try running the `simple_window` example of https://github.com/vberger/wayland-window on tag v0.2.2 ? Can you move and resize it ? I'm trying to figure if the issue is in glutin, or in one of my wayland crates.

The cursor doesn't yet change on the borders to reflect the fact that you can resize, but resizing should work.

**Comment by Binero** [comment]
I tried testing on tag v0.2.2. The window is not resizable, the window is not movable. 

I also tried testing on the master branch. The window still doesn't allow resizing or moving, but the cursor does update to hint at resizing.

**Comment by vberger** [comment]
Ok, it's a bug to be fixed in wayland-window then, let's continue here: https://github.com/vberger/wayland-window/issues/8

**Comment by vberger** [comment]
All this belongs to winit now
